{
    'map': {'driver_origin_x': ['uniform', 0, 20],
            'driver_origin_y': ['uniform', 0, 20],
            'rider_origin_x': ['uniform', 0, 20],
            'rider_origin_y': ['uniform', 0, 20],
            'rider_destination_x': ['uniform', 0, 20],
            'rider_destination_y': ['uniform', 0, 20],
            },

    # 'map': {'driver_origin_x': ['beta', 1.920, 2.083, 0, 20],
    #         'driver_origin_y': ['beta', 2.261, 1.766, 0, 20],
    #         'rider_origin_x': ['beta', 1.355, 2.980, 0, 20],
    #         'rider_origin_y': ['beta', 1.590, 2.312, 0, 20],
    #         'rider_destination_x': ['beta', 1.596, 1.817, 0, 20],
    #         'rider_destination_y': ['beta', 2.076, 1.575, 0, 20],
    #         },
    'drivers': {
        'inter_arrival': ['exponential', 0.05],
        'jobs_time': ['uniform', 300, 480],
        'petrol_cost': 0.2
    },
    'riders': {
        'inter_arrival': ['exponential', 0.5],
        'wait_time': ['exponential', 0.083333333333],
        'initial_pay_rate': 3,
        'pay_rate': 2
    },
    'trip': {
        'avg_travel_speed': 0.3333333333333333,
        'actual_trip_bound': ['uniform', 0.8, 1.2]
    },
    'simulation': {
        'termination': 144000,
        'name': 'improved',
        'n_snaps': 10,
        'waiting_points': True,
        'search_while_dropping': False,
        'drivers_break': False,
        'maximum_match_range': True,
    },
    'search_while_dropping': {'time_to_search': 30,},
    'drivers_break': {'jobs_time': 180,
                      'break_time': 15},
    'maximum_match_range': {max_range: 10}
    }
